### ISSUE TITLE
Check if htaccess is allowed if server is apache

### ISSUE THREAD

**Issue by piotrpog** [pixelandtonic/craft-server-check#13]
I recently used this script on new server and everything seemed ok. 
But after uploading Craft, i found out that `Allowoverride` is set to `None` and htaccess files are not allowed, this resulted in subpages and admin panel not working.
Maybe if server is apache, server check script should check if htaccess files are allowed?

**Comment by angrybrad** [comment]
It doesn't seem like there's going to be a reliable, non-hacky, non-brittle way to check for that from PHP, unfortunately. https://stackoverflow.com/questions/7137104/check-allowoverride-value-using-php
