### ISSUE TITLE
Database checks not performed even after supplying database credentials in db.php

### ISSUE THREAD

**Issue by sidm1983** [pixelandtonic/craft-server-check#14]
### Description
This is a bug report for the craftcms server-check code. The database credentials in the db.php file are not being fetched/referenced by the RequirementsChecker.php file. As a result, no database checks are ever performed even if correct credentials are supplied in the db.php file.

### Steps to reproduce

1. Place valid pgsql or mysql credentials in the db.php file
2. Reload the `/checkit.php` page and you will see that the two additional database checks (PDO PostgreSQL extension & PostgreSQL 9.5+) are missing in the final details table.

I was able to figure out the issue by putting in the following 2 `echo` statements in the `catch(PDOException $e)` block in the `getDbConnection()` function in the `RequirementsChecker.php` file:
```
echo 'Caught exception: ',  $e->getMessage(), "<br/>";
echo 'Data source name: ', $this->dsn, "<br/>";
```
The first echo statement above returned an 'Invalid data source name' message and the second one showed that `$this->dsn` did not have a value, which suggested that the values in the `db.php` file were not being referenced or fetched.

I was able to get it working by hard-coding the values for `$this->dsn`, `$this->dbUser` and `$this->dbPassword` just before the code creates the new PDO connection object. Once I did this, the above two echo statements were no longer being executed and the two additional database checks appeared in the final details table on the `/checkit.php` page.

I personally don't need this fixed as I was able to workaround the issue and get the database checks working, but just wanted to report it as there is a good chance people won't realize that the database checks didn't actually run.

Thank you.

### Additional info

- Craft version: NA
- PHP version: 7.3.15
- Database driver & version: pgsql
- Plugins & versions:

**Comment by brandonkelly** [comment]
Looks like checking the DB server’s requirements from `checkit.php` was removed in 6e7ecc427b5252b8b878f028a45738e19e7968b9, and the documentation was just never updated for it. So just… fixed the glitch… by updating the README and other docs.

**Comment by sidm1983** [comment]
@brandonkelly, I see. That's good to know.

Apart from updating the readme and deleting the `db.php` config file, shouldn't any and all code relating to database checks be removed from the `RequirementsChecker.php` & `requirements.php` files as well to avoid future confusion? Just a thought.

Thanks for the info.

**Comment by brandonkelly** [comment]
The DB checks are still used when run within Craft CMS – just not when this script is run as a standalone thing.
