### ISSUE TITLE
Server check does not verify json.

### ISSUE THREAD

**Issue by janson** [pixelandtonic/craft-server-check#7]
json is a [required extension](https://docs.craftcms.com/v3/requirements.html#required-php-extensions), but server check doesn't verify. 

On a Rackspace Cloud server, I ran into an obscure "An internal server error occurred." I tracked this down to `Error: Call to undefined function yii\helpers\json_decode()` when bootstrapping (vendor/yiisoft/yii2/helpers/BaseJson.php:106)

**Comment by angrybrad** [comment]
Fixed in https://github.com/craftcms/server-check/commit/bb451a8c99185ccf60cbcdc21ae579d65794a0de
